Repository hs921ig/Hacktoberfest-2021-Competitive-coding-resources-, pull requests merged in 2021-10, with the labels that each got.

#1 Add LICENSE
  LICENSE
Labels: hactoberfest-accepted

#2 Create searchandsort.c
  searchandsort.c
Labels: hactoberfest-accepted

#3 Update README.md
  README.md
Labels: hactoberfest-accepted

#4 Add file swap_new1.c
  swap_new1.c
Labels: hactoberfest-accepted

#6 Update linkedlist.c
  linkedlist.c
Labels: hactoberfest-accepted

#5 Update linkedlist.c
  linkedlist.c
Labels: hacktoberfest-accepted

#7 Create functions.c
  functions.c
Labels: hactoberfest-accepted, hacktoberfest-accepted

#8 Create swap.c
  Question3.c
  swap.c
Labels: hactoberfest, hactoberfest-accepted, hacktoberfest-accepted

#10 Add files via upload
  Q2_third.c
  quadroots.c
Labels: hactoberfest, hactoberfest-accepted, hacktoberfest-accepted, hacktoberfest

#11 Add files via upload
  Q2_second.c
Labels: hactoberfest, hactoberfest-accepted, hacktoberfest-accepted, hacktoberfest

#12 Create pr.c
  pr.c
Labels: hacktoberfest-accepted, hacktoberfest

#13 Create ops.cpp
  ops.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#14 Create new_1.c
  new_1.c
Labels: hacktoberfest-accepted, hacktoberfest

#15 Create practicenew.c
  practicenew.c
Labels: hacktoberfest-accepted, hacktoberfest
